# Generated by Django 5.1 on 2024-09-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
