# Generated by Django 5.1 on 2024-09-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dishtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
